  
version: '2'

tasks:
  start-local:
    cmds:
      - npm run build && REDIS_HOST="localhost" REDIS_PORT=6379 DB_HOST="localhost" DB_NAME="postgres" DB_USER="postgres" DB_PASS="secret" npm run start
